language: objective-c
os: osx
osx_image: xcode9.4

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - PROJECT=MoreCodable.xcodeproj
    - CONFIG=Release
    - ACTION="build-for-testing test-without-building"

branches:
  only: 
    - master

cache:
  directories:
    - Carthage

matrix:
  include:
    - env: JOB=pod_lint
      script:
        - pod lib lint --quick
    - env: JOB=xcode SCHEME=MoreCodable SDK=iphonesimulator

script:
  - set -o pipefail
  - xcodebuild $ACTION -project $PROJECT -scheme $SCHEME -sdk $SDK -destination 'name=iPhone 7,OS=11.2' -configuration $CONFIG ENABLE_TESTABILITY=YES | xcpretty

notifications:
  email: false

